# Generated by Django 3.2.8 on 2021-11-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskeysandtokens',
            name='url',
        ),
    ]
