# Generated by Django 3.2.8 on 2021-11-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_accesskeysandtokens_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskeysandtokens',
            name='url',
            field=models.UUIDField(null=True),
        ),
    ]
