# Generated by Django 3.2.8 on 2021-11-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_accesskeysandtokens_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskeysandtokens',
            name='twitter_access_token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesskeysandtokens',
            name='twitter_access_token_secret',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
