# Generated by Django 3.2.8 on 2021-12-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211201_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskeysandtokens',
            name='twitter_access_token',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='accesskeysandtokens',
            name='twitter_access_token_secret',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='accesskeysandtokens',
            name='twitter_api_key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='accesskeysandtokens',
            name='twitter_bearer_token',
            field=models.BinaryField(),
        ),
    ]
